# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Lab4/PYNQ-Z1_C.xdc

# Block Designs: bd/CPU_0/CPU_0.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_0 || ORIG_REF_NAME==CPU_0} -quiet] -quiet

# IP: bd/CPU_0/ip/CPU_0_processing_system7_0_0/CPU_0_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_0_processing_system7_0_0 || ORIG_REF_NAME==CPU_0_processing_system7_0_0} -quiet] -quiet

# IP: bd/CPU_0/ip/CPU_0_axi_regmap_0_0/CPU_0_axi_regmap_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_0_axi_regmap_0_0 || ORIG_REF_NAME==CPU_0_axi_regmap_0_0} -quiet] -quiet

# IP: bd/CPU_0/ip/CPU_0_xbar_0/CPU_0_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_0_xbar_0 || ORIG_REF_NAME==CPU_0_xbar_0} -quiet] -quiet

# IP: bd/CPU_0/ip/CPU_0_ps7_0_axi_periph_0/CPU_0_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_0_ps7_0_axi_periph_0 || ORIG_REF_NAME==CPU_0_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/CPU_0/ip/CPU_0_rst_ps7_0_100M_0/CPU_0_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_0_rst_ps7_0_100M_0 || ORIG_REF_NAME==CPU_0_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/CPU_0/ip/CPU_0_CPU_0_0/CPU_0_CPU_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_0_CPU_0_0 || ORIG_REF_NAME==CPU_0_CPU_0_0} -quiet] -quiet

# IP: bd/CPU_0/ip/CPU_0_blk_mem_gen_0_0/CPU_0_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_0_blk_mem_gen_0_0 || ORIG_REF_NAME==CPU_0_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/CPU_0/ip/CPU_0_xlconstant_0_0/CPU_0_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_0_xlconstant_0_0 || ORIG_REF_NAME==CPU_0_xlconstant_0_0} -quiet] -quiet

# IP: bd/CPU_0/ip/CPU_0_xlconcat_0_0/CPU_0_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_0_xlconcat_0_0 || ORIG_REF_NAME==CPU_0_xlconcat_0_0} -quiet] -quiet

# IP: bd/CPU_0/ip/CPU_0_axi_bram_ctrl_0_0/CPU_0_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_0_axi_bram_ctrl_0_0 || ORIG_REF_NAME==CPU_0_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/CPU_0/ip/CPU_0_auto_pc_0/CPU_0_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_0_auto_pc_0 || ORIG_REF_NAME==CPU_0_auto_pc_0} -quiet] -quiet

# XDC: bd/CPU_0/CPU_0_ooc.xdc
